name: CI testing and linting with Node.js

on: [push]

jobs:
  lintAndTest:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: make i
    - run: make lint
    - run: make test
      env:
        CI: true