name: 'CI linting and testing'

on: 
  push: 
    branches: 
      - master

jobs:   
  linting:
    name: 'Run linting and testing'
    runs-on: ubuntu-latest
    steps:
      name: 'My first step'
      with:
          node-version: 12.x
      run: make lint
      run: make test

